:root{--bg:#0a0a0f;--surface:#111118;--surface2:#1a1a24;--border:#2a2a3a;--accent:#e8c840;--accent2:#ff6b35;--text:#e8e8f0;--muted:#888899;--link:#60aaff;--green:#4caf7d;--red:#ff5252}
*{margin:0;padding:0;box-sizing:border-box}
body{background:var(--bg);color:var(--text);font-family:'DM Sans',sans-serif;min-height:100vh;background-image:radial-gradient(ellipse 80% 60% at 50% -10%,rgba(232,200,64,.07) 0%,transparent 60%)}
header{background:linear-gradient(180deg,rgba(232,200,64,.08) 0%,transparent 100%);border-bottom:1px solid var(--border);padding:24px 20px 18px;position:sticky;top:0;z-index:100;backdrop-filter:blur(20px)}
.ht{display:flex;align-items:baseline;gap:14px;margin-bottom:14px;flex-wrap:wrap}
h1{font-family:'Bebas Neue',sans-serif;font-size:clamp(2.2rem,5vw,3.4rem);letter-spacing:3px;background:linear-gradient(135deg,var(--accent) 0%,#fff7c0 50%,var(--accent2) 100%);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text;line-height:1}
.badge{background:var(--surface2);border:1px solid var(--border);color:var(--accent);font-size:.72rem;font-weight:700;letter-spacing:1px;padding:4px 12px;border-radius:20px;text-transform:uppercase;white-space:nowrap}
.ctrl{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.sw{position:relative;flex:1;min-width:200px}.si{position:absolute;left:13px;top:50%;transform:translateY(-50%);color:var(--muted);pointer-events:none}
input[type=text]{width:100%;background:var(--surface2);border:1px solid var(--border);color:var(--text);font-family:'DM Sans',sans-serif;font-size:.93rem;padding:10px 14px 10px 40px;border-radius:10px;outline:none;transition:border-color .2s,box-shadow .2s}
input[type=text]:focus{border-color:var(--accent);box-shadow:0 0 0 3px rgba(232,200,64,.12)}input[type=text]::placeholder{color:var(--muted)}
.fbs{display:flex;gap:5px}.fb{background:var(--surface2);border:1px solid var(--border);color:var(--muted);font-family:'DM Sans',sans-serif;font-size:.76rem;font-weight:500;padding:8px 12px;border-radius:8px;cursor:pointer;transition:all .15s;white-space:nowrap}.fb:hover,.fb.active{background:var(--accent);border-color:var(--accent);color:#000;font-weight:700}
.ab{background:linear-gradient(135deg,var(--accent2),#ff8c5a);border:none;color:#fff;font-family:'DM Sans',sans-serif;font-size:.84rem;font-weight:700;padding:10px 18px;border-radius:10px;cursor:pointer;transition:all .18s;white-space:nowrap;box-shadow:0 4px 16px rgba(255,107,53,.3)}.ab:hover{transform:translateY(-1px);box-shadow:0 6px 24px rgba(255,107,53,.45)}
.ov{display:none;position:fixed;inset:0;background:rgba(0,0,0,.75);z-index:200;align-items:center;justify-content:center;backdrop-filter:blur(6px)}.ov.open{display:flex}.modal{background:var(--surface);border:1px solid var(--border);border-radius:16px;padding:28px;width:min(460px,92vw);box-shadow:0 24px 64px rgba(0,0,0,.6);animation:mIn .22s cubic-bezier(.34,1.56,.64,1)}@keyframes mIn{from{transform:scale(.9) translateY(16px);opacity:0}to{transform:scale(1);opacity:1}}
.modal h2{font-family:'Bebas Neue',sans-serif;font-size:1.7rem;letter-spacing:2px;color:var(--accent);margin-bottom:18px}.field{margin-bottom:12px}.field label{display:block;font-size:.75rem;font-weight:600;letter-spacing:.8px;text-transform:uppercase;color:var(--muted);margin-bottom:5px}.field input{padding:10px 13px}.ma{display:flex;gap:10px;margin-top:20px}.bs{flex:1;background:var(--accent);border:none;color:#000;font-family:'DM Sans',sans-serif;font-size:.9rem;font-weight:700;padding:12px;border-radius:8px;cursor:pointer;transition:opacity .15s}.bs:hover{opacity:.88}.bs:disabled{opacity:.5;cursor:not-allowed}.bc{background:var(--surface2);border:1px solid var(--border);color:var(--muted);font-family:'DM Sans',sans-serif;font-size:.9rem;padding:12px 18px;border-radius:8px;cursor:pointer}
main{max-width:860px;margin:0 auto;padding:20px 14px 60px}.stats{display:flex;gap:20px;margin-bottom:18px;font-size:.81rem;color:var(--muted)}.stats span{font-weight:600;color:var(--text)}#loading{text-align:center;padding:60px 20px;color:var(--muted)}#noRes{display:none;text-align:center;padding:60px 20px;color:var(--muted)}.ml{display:flex;flex-direction:column;gap:2px}.row{display:flex;align-items:center;gap:13px;padding:12px 14px;border-radius:10px;border:1px solid transparent;transition:background .15s,border-color .15s}.row:hover{background:var(--surface2);border-color:var(--border)}.row.new{animation:hl 2.5s ease forwards}@keyframes hl{0%{background:rgba(232,200,64,.18);border-color:rgba(232,200,64,.4)}100%{background:transparent;border-color:transparent}}
.num{font-family:'Bebas Neue',sans-serif;font-size:.93rem;color:var(--muted);min-width:34px;text-align:right;flex-shrink:0}.dot{width:5px;height:5px;border-radius:50%;background:var(--border);flex-shrink:0;transition:background .2s}.row:hover .dot{background:var(--accent)}.name{flex:1;font-size:.95rem;color:var(--text);line-height:1.4}.dl{flex-shrink:0;font-size:.73rem;font-weight:600;color:var(--link);text-decoration:none;background:rgba(96,170,255,.1);border:1px solid rgba(96,170,255,.2);padding:4px 9px;border-radius:6px;transition:all .15s;white-space:nowrap}.dl:hover{background:rgba(96,170,255,.2);color:#90c8ff}.edit,.del{flex-shrink:0;background:none;border:none;color:transparent;cursor:pointer;font-size:.9rem;width:26px;height:26px;border-radius:6px;display:flex;align-items:center;justify-content:center;transition:all .15s}.row:hover .edit,.row:hover .del{color:var(--muted)}.edit:hover{background:rgba(232,200,64,.15)!important;color:var(--accent)!important}.del:hover{background:rgba(255,82,82,.15)!important;color:var(--red)!important}
#toast{position:fixed;bottom:24px;left:50%;transform:translateX(-50%);background:var(--surface);border:1px solid var(--green);color:var(--green);padding:11px 20px;border-radius:10px;font-size:.86rem;font-weight:600;z-index:999;max-width:90vw;text-align:center;box-shadow:0 8px 32px rgba(0,0,0,.5);opacity:0;transition:opacity .3s;pointer-events:none}#toast.err{border-color:var(--red);color:var(--red)}#toast.show{opacity:1}.spin{display:inline-block;width:14px;height:14px;border:2px solid rgba(0,0,0,.3);border-top-color:#000;border-radius:50%;animation:sp .7s linear infinite;vertical-align:middle;margin-right:4px}@keyframes sp{to{transform:rotate(360deg)}}
